final List<String> treeImages = const [
    'tree-1.png',
    'tree-2.png',
    'tree-3.png',
    'tree-4.png',
    'tree-5.png',
    'tree-6.png',
    'tree-7.png',
    'tree-8.png',
    'tree-9.png',
    'tree-10.png',
    'tree-11.png',
    'tree-12.png',
    'tree-13.png',
  ];
