name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment file from template 
        run: cp .env.stencil .env 

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      - name: Install dependencies
        run: flutter pub get

      - name: Dart analyze
        run: flutter analyze

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Flutter build (apk)
        run:  flutter build apk --release --no-tree-shake-icons 2>/dev/null | grep -v "deprecated"
